//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewRequest.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewRequestEntities : DbContext
    {
        public NewRequestEntities()
            : base("name=NewRequestEntities")
        {
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllLevel> AllLevels { get; set; }
        public virtual DbSet<CloseSector> CloseSectors { get; set; }
        public virtual DbSet<Code> Codes { get; set; }
        public virtual DbSet<CurrentSituation> CurrentSituations { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameTask> GameTasks { get; set; }
        public virtual DbSet<GameTip> GameTips { get; set; }
        public virtual DbSet<LevelType> LevelTypes { get; set; }
        public virtual DbSet<Ranking> Rankings { get; set; }
        public virtual DbSet<Statistic> Statistics { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserStatu> UserStatus { get; set; }
        public virtual DbSet<UserTeamStatu> UserTeamStatus { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
